name: Django CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:  
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate staticfiles
        run: |
           python manage.py collectstatic --noinput

      - name: Run Tests
        run: |
          python manage.py test

      - name: Linting
        run: |
          flake8

      - name: Run tests with coverage
        if: steps.linting.outcome == ''
        run: |
          coverage run --source='.' manage.py test
          coverage report --fail-under=80

  build_and_push_docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - name: Build Docker image
        run: |
          docker build . \
          --file Dockerfile \
          --tag oc_lettings_site: $(git rev-parse --short HEAD) \
          --tag lahlou1973/oc_lettings_site:latest
  
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
  
      - name: Push Docker image to Docker Hub
        run: |
          docker push lahlou1973/oc_lettings_site:latest
      
  trigger_render_deployment:
    name: Trigger Render Deployment
    runs-on: ubuntu-latest
    needs: [build_and_push_docker]
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cntiobfsc6pc73cblgfg?key=UvhYD9esvEo&imgURL=docker.io%2Flahlou1973%2Foc_lettings_site%3Alatest"
