name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
   
  build:
    name: oc_lettings_site Continious Integration
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate staticfiles
        run: |
           python manage.py collectstatic --noinput   
      - name: Run Tests
        run: |
          python manage.py test
      - name: Linting
        run: |
          flake8
      - name: Run tests with coverage
        if: steps.linting.outcome == ''
        run: |
          coverage run --source='.' manage.py test
          coverage report --fail-under=80