name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: oc_lettings_site Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - name: Set Git Commit Message
        id: git_message
        run: echo "COMMIT_MESSAGE=$(git log --format=%B -n 1 | tr -d '\n' | tr -cd '[:alnum:]-._')" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate staticfiles
        run: |
           python manage.py collectstatic --noinput   
      - name: Run Tests
        run: |
          python manage.py test
      - name: Linting
        run: |
          flake8
      - name: Run tests with coverage
        if: steps.linting.outcome == ''
        run: |
          coverage run --source='.' manage.py test
          coverage report --fail-under=80
      - name: Build and push Docker image
        run: |
          docker build . \
          --file Dockerfile \
          --tag oc_lettings_site:${{ env.MESSAGE }} \
          --tag lahlou1973/oc_lettings_site:latest
  
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
  
      - name: Push Docker image to Docker Hub
        run: |
          docker push lahlou1973/oc_lettings_site:latest
