name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Git Commit Message
        id: git_message
        run: echo "MESSAGE=$(git log --format=%B -n 1 | tr -d '\n' | tr -cd '[:alnum:]-._')" >> $GITHUB_ENV

      - name: Initialize Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 coverage
          pip install -r requirements.txt

      - name: Linting
        run: |
          flake8

      - name: Run tests with coverage
        run: |
          coverage run --source='.' manage.py test
          coverage report --fail-under=80
